<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Chats\Queries\GetAllChats\" />
  </ItemGroup>
</Project>
